const express=require('express')
const router=express.Router()
const userRegister=require("../controllers/users controller/register")
const otpSent = require('../controllers/users controller/otpGenerator')
const otpAuth = require('../middlewares/nodeMailerAuth')
const login = require('../controllers/users controller/login')
const forgetPassword = require('../controllers/users controller/forgetPassword')
const resetPassword = require('../controllers/users controller/resetPassword')
const {authLimiter,otpLimiter}=require('../middlewares/api limiter/separateApiLimiter')
const { jwtAuth } = require('../middlewares/jwt Auth/jwtAuthMiddleware')
const createpayment = require('../controllers/users controller/createPayment')
const verifyPayment = require('../controllers/users controller/verifyPayment')
const existingSubscription = require('../middlewares/existingSubscription')
const courseEntroll = require('../controllers/users controller/courseEntroll')
const { getLectureUrlByCourseTitle } = require('../controllers/users controller/coursePlayUrl')
const updateWatchTime = require('../controllers/users controller/updateWatchTime')
const courseLike = require('../controllers/users controller/CourseLike')

router.post("/auth/register",[authLimiter,otpAuth],userRegister)
router.post("/auth/otpSent",otpLimiter,otpSent)
router.post("/auth/login",authLimiter,login)
router.post('/auth/forgetPassword',otpLimiter,forgetPassword)
router.post('/auth/resetPassword',resetPassword)
router.post("/payment/purchaseSubscription",jwtAuth,existingSubscription, createpayment)
router.post("/payment/verifyPayment",jwtAuth,verifyPayment)
router.post("/course/entroll/:id",jwtAuth,courseEntroll)
router.get("/course/:courseId/:courseTitle",jwtAuth,getLectureUrlByCourseTitle)
router.post("/course/updateWatchTime",jwtAuth,updateWatchTime)
router.post("/course/like",jwtAuth,courseLike)

module.exports=router